### ISSUE TITLE
AUR dotnet dependencies

### ISSUE THREAD

**Issue by brettinternet** [unfrl/dug#1]
The [dug-git AUR package](https://aur.archlinux.org/packages/dug-git/) lists `dotnet-sdk-bin` and `dotnet-host-bin` as dependencies. Is it possible to broaden this requirement? For example, `dotnet-sdk` could require:

```
dotnet-sdk>=5.0.0 (dotnet-sdk-preview, dotnet-sdk-bin) 
```

Also, this project looks great! Thank you.

**Comment by elliothatch** [comment]
Thanks for the feedback! This is actually the first AUR package I've made, so there are a lot of things I still don't know about. I'll make the change as soon as I can.

**Comment by brettinternet** [comment]
I've never created one myself, but I'd be happy to help figure it out. I notice that a lot of packages are able to require _one of_ a list of satisfying dependencies, such as https://aur.archlinux.org/packages/jackett/ which requires `dotnet-sdk>=5.0.0 (dotnet-sdk-2.2, dotnet-sdk-2.2-vs2017, dotnet-sdk-3.0, dotnet-sdk-2.1, dotnet-sdk-preview, dotnet-sdk-3.1, dotnet-sdk-bin) (make)`, if I'm reading that right. Thank you for adding this to AUR.

**Comment by elliothatch** [comment]
Thanks for the help, I've pushed the changes to the AUR, I think it should work now with any packages that provide dotnet >= 5.0.0

**Comment by brettinternet** [comment]
I see, you also had to specify those dependencies as make deps. I wonder why the build still used the AUR binaries rather than the dotnet libs from `community`.

```
community/dotnet-sdk 3.1.8.sdk108-1 [installed]
    The .NET Core SDK
```

Your dependency list looks like it should include `dotnet-sdk` as an acceptable dep, but I still ran into this when building with yay.

```
$ yay -S dug-git
:: There are 2 providers available for dotnet-sdk>=5.0.0,:
:: Repository AUR
    1) dotnet-sdk-bin 2) dotnet-sdk-preview

Enter a number (default=1):
:: There are 4 providers available for dotnet-host>=5.0.0:
:: Repository AUR
    1) dotnet-host-bin 2) dotnet-host-bin 3) dotnet-host-preview 4) dotnet-host-preview

Enter a number (default=1):
:: There are 2 providers available for dotnet-runtime>=5.0.0:
:: Repository AUR
    1) dotnet-runtime-bin 2) dotnet-runtime-preview

Enter a number (default=1):
```

This isn't a very big problem since make dependencies can be removed after the install, but I'm wondering if I understand this correctly.

**Comment by elliothatch** [comment]
It's not using the official community package because it hasn't been updated to .NET 5 yet (still at 3.1.8). That's why I originally specified the AUR "bin" variants before you told me I can use version designators. I guess the hosts conflict, but my understanding is that the dotnet-host will work with all lower versions of .NET, so you can use the .NET 5 bin version with older SDKs and runtimes.

**Comment by elliothatch** [comment]
Or you can manually revert back to the community dotnet-host after the build is finished, since the runtime is now included in the built binary.

**Comment by brettinternet** [comment]
Ah, thank you for pointing that out to me. I see the discrepancy now. Thanks for updating this.
