### ISSUE TITLE
Lowercase query options

### ISSUE THREAD

**Issue by tk-nguyen** [unfrl/dug#11]
Hello, I've been using this tool for several days and I'm loving it so far! 
However, there's one minor issue: the tool does not recognize query types in lowercase (`a` instead of `A`, `txt` instead of `TXT`, `mx` instead of `MX`, etc...). I'm not familiar with C# per se, but I think this can be fixed by converting all query types to uppercase.
It would be better if `dug` behaved like `dig`, which is parsing query types when they're specified in place of the "verbs" i.e. `dug mx example.com`, since `dug` by default run with the verb "run".
Thank you for creating this tool!

**Comment by MattInternet** [comment]
Hey @tk-nguyen , I created #15 to capture your second idea. Also thanks for the issue! :)

**Comment by tk-nguyen** [comment]
Thanks for being so quick in fixing it :+1: !
