### ISSUE TITLE
Add to homebrew

### ISSUE THREAD

**Issue by MattInternet** [unfrl/dug#3]
"Itd be cool"™ if dug was distributable via homebrew. I think it owuld be best if it supported both linux and osx, both of which we are currently building in the ci/cd.

I've never packaged anything with homebrew, heres some documentation:
https://docs.brew.sh/Adding-Software-to-Homebrew

Annoyingly I havent found an example of a dotnet app being distributed via homebrew, Im sure its possible though.

**Comment by dimitre** [comment]
+1 for this. 
Some brew formulas can have pre compiled software (binary releases)

**Comment by MattInternet** [comment]
Adding to Linux Homebrew here: https://github.com/Homebrew/linuxbrew-core/pull/23837

If that goes well I'll borrow a macbook and try to get it onto the mac homebrew

I have no idea how homebrew works, but this Formula appears to work locally so hopefully its all good :sweat_smile:

**Comment by dimitre** [comment]
@MattInternet let me know if I can help with testing macOs formula

**Comment by MattInternet** [comment]
@dimitre I tried adding dug to normal (mac) homebrew here: https://github.com/Homebrew/homebrew-core/pull/81465

But they dont seem to like the license. I'll watch the linuxbrew one but I wouldnt be surprised if it fails for the same reason. In the link the moderator posted it mentioned them preferring non-binaries. I could try that but it might be a while until I want to battle Ruby to do it, if you'd like to give it a swing that'd be awesome. That still doesnt address the license issue though :disappointed:

**Comment by MattInternet** [comment]
Gonna close this since it looks like Homebrew wont accept dug's license
