### ISSUE TITLE
mark 0.0.93 as latest release

### ISSUE THREAD

**Issue by chenrui333** [unfrl/dug#49]
👋 right now the latest release points to 0.0.92, it would be nice to mark 0.0.93 as latest release, thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/192974

**Comment by MattInternet** [comment]
There is a problem with the CI blocking the publishing of the snap package and the github release, I probably wont be able to look into it until next weekend 😬

**Comment by MattInternet** [comment]
It was an easy fix, 0.0.93 should be the latest release now!

**Comment by chenrui333** [comment]
@MattInternet thanks for the quick turnaround, I just realized 0.0.94 is actually the latest, can you mark that as the latest instead? Thanks! :)


<img width="627" alt="image" src="https://github.com/user-attachments/assets/14349467-71d3-450c-b01f-f889b7c12144">

**Comment by MattInternet** [comment]
@chenrui333 0.0.94 should be the latest now

**Comment by chenrui333** [comment]
thank you!!
